baseURL = 'https://savvas.live'
languageCode = 'en-us'
title = 'Savvas Blog ğŸ“–'
theme = 'PaperMod'

[params]
 
  hideFooter = 'true'
  ShowPostNavLinks = 'false'
  
  #menu
  [menu]
    [[menu.main]]
    identifier = "archives"
    name = "archives"
    url = "/archives/"

  # homeinfomode
  [params.homeInfoParams]
    imageUrl = "<https://imgur.com/a/9q4nTCg>"
	imageWidth = 120
	imageHeight = 120
    Title = "Hey"
    Content = "Iâ€™m Savvas, ğŸ”‘Privacy, ğŸ•¸ï¸Networks & ğŸ®Video Games lover."
	
    [[params.socialIcons]]
      name = "<mastodon.social>"
      url = "https://fosstodon.org/@sio"
	  
	  
